a5lab/axion

README.md
pom.xml

Fix readme

---

ansible/roles/app/templates/etc/systemd/system/tabr.service.j2
src/main/resources/logback-spring.xml

add success code

---

ansible/main.yml
ansible/roles/postgresql/defaults/main.yml
ansible/roles/postgresql/handlers/main.yml
ansible/roles/postgresql/tasks/main.yml

add postgresql

---

docker/postgresql.yml

change passwrod

---

README.md
src/main/resources/static/js/home.js
src/main/resources/static/js/home.min.js
src/main/resources/templates/home.html

add handler

---

src/test/java/com/a5lab/tabr/domain/tenants/TenantMapperTest.java

add a new tests to tenant mapper

add a new tests to tenant mapper

---

src/main/java/com/a5lab/tabr/controllers/TenantsApiController.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantService.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantServiceImpl.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantsApiController.java

add api controller

---

.github/actions/jdk/action.yml
.github/actions/nodejs/action.yml
.github/workflows/build.yml
.github/workflows/release.yml
README.md

Add ci to build

---

.github/workflows/deploy.yml
.github/workflows/package.yml

Add deploy adhocs

---

.github/workflows/deploy.yml
.github/workflows/package.yml
.github/workflows/release.yml
.github/workflows/verify.yml

Deploy and release actions implementations

Deploy and release actions implementations

---

README.md
ansible/roles/app/defaults/main.yml
ansible/roles/app/tasks/application.yml
ansible/roles/app/templates/etc/systemd/system/tabr.service.j2

Add readme to delete database and fix issue to build tabr at server

Add readme to delete database

---

src/main/java/com/a5lab/tabr/config/MessageConfiguration.java
src/main/java/com/a5lab/tabr/domain/radars/Radar.java
src/main/java/com/a5lab/tabr/domain/radars/RadarDto.java
src/main/java/com/a5lab/tabr/domain/radars/RadarMapper.java
src/main/java/com/a5lab/tabr/domain/radars/RadarService.java
src/main/java/com/a5lab/tabr/domain/radars/RadarServiceImpl.java
src/main/java/com/a5lab/tabr/domain/radars/RadarsApiController.java
src/main/java/com/a5lab/tabr/domain/radars/RadarsController.java
src/main/java/com/a5lab/tabr/utils/EntityToDtoMapper.java
src/main/resources/database/data/radars_en.csv
src/main/resources/database/migrations/2022_12_10_0000_create_radars_table.xml
src/main/resources/messages/radar.properties
src/main/resources/messages/radar_de.properties
src/main/resources/templates/settings/radars/add.html
src/main/resources/templates/settings/radars/edit.html
src/main/resources/templates/settings/radars/index.html
src/main/resources/templates/settings/radars/show.html
src/test/java/com/a5lab/tabr/domain/radars/RadarMapperTests.java
src/test/java/com/a5lab/tabr/domain/radars/RadarsApiControllerTests.java

Add radar gui

---

src/main/java/com/a5lab/tabr/domain/rings/Ring.java
src/main/java/com/a5lab/tabr/domain/segments/Segment.java

Fix update for ring & segment

---

src/main/resources/templates/settings/tenants/add.html
src/main/resources/templates/settings/tenants/edit.html
src/main/resources/templates/settings/tenants/fieldset.html

Purpose to work with form

---

src/main/java/com/a5lab/tabr/domain/blips/BlipsCfgController.java
src/main/java/com/a5lab/tabr/domain/entries/EntriesCfgController.java
src/main/java/com/a5lab/tabr/domain/radars/RadarsCfgController.java
src/main/java/com/a5lab/tabr/domain/rings/RingsCfgController.java
src/main/java/com/a5lab/tabr/domain/segments/SegmentsCfgController.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantsCfgController.java
src/main/resources/templates/settings/blips/index.html
src/main/resources/templates/settings/radars/index.html
src/main/resources/templates/settings/rings/index.html
src/main/resources/templates/settings/segments/index.html
src/main/resources/templates/settings/tenants/index.html
src/test/java/com/a5lab/tabr/domain/tenants/TenantsCfgControllerTests.java

Add paging for all models

---

src/main/java/com/a5lab/tabr/domain/blips/BlipService.java
src/main/java/com/a5lab/tabr/domain/blips/BlipServiceImpl.java
src/main/java/com/a5lab/tabr/domain/blips/BlipsApiController.java
src/main/java/com/a5lab/tabr/domain/blips/BlipsCfgController.java
src/main/java/com/a5lab/tabr/domain/entries/EntriesApiController.java
src/main/java/com/a5lab/tabr/domain/entries/EntryService.java
src/main/java/com/a5lab/tabr/domain/entries/EntryServiceImpl.java
src/main/java/com/a5lab/tabr/domain/radars/RadarService.java
src/main/java/com/a5lab/tabr/domain/radars/RadarServiceImpl.java
src/main/java/com/a5lab/tabr/domain/radars/RadarsApiController.java
src/main/java/com/a5lab/tabr/domain/rings/RingService.java
src/main/java/com/a5lab/tabr/domain/rings/RingServiceImpl.java
src/main/java/com/a5lab/tabr/domain/rings/RingsApiController.java
src/main/java/com/a5lab/tabr/domain/segments/SegmentService.java
src/main/java/com/a5lab/tabr/domain/segments/SegmentServiceImpl.java
src/main/java/com/a5lab/tabr/domain/segments/SegmentsApiController.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantServiceImpl.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantsApiController.java
src/main/resources/templates/settings/blips/fields.html
src/test/java/com/a5lab/tabr/domain/radars/RadarsApiControllerTests.java

Use dto at view layer and sort view layer

Use dto at view layer

---

pom.xml

remove findsec bugs

---

src/main/java/com/a5lab/tabr/domain/blips/BlipsCfgController.java
src/main/java/com/a5lab/tabr/domain/entries/EntriesCfgController.java
src/main/java/com/a5lab/tabr/domain/radars/RadarsCfgController.java
src/main/java/com/a5lab/tabr/domain/rings/RingsCfgController.java
src/main/java/com/a5lab/tabr/domain/segments/SegmentsCfgController.java
src/main/java/com/a5lab/tabr/domain/tenants/TenantsCfgController.java
src/main/resources/application.yml

Make paging size as configuration parameters

Make paging size as configuration parameters

---

docs/modules/installation/pages/system_requirements.adoc

@arufanov 
1. Can you provide more specific system requirements for AXION? (I don't think that nexus's are appropriate)
2. What DB we specify for use?
3. I don't think that "Dedicated operating system user account" section is required...

252 docs system requirements

---

src/main/java/com/a5lab/axion/domain/ring/Ring.java
src/main/java/com/a5lab/axion/domain/ring/RingCfgController.java
src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java

Create tests for rings

---

src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgController.java
src/main/resources/messages/technology_blip.properties
src/main/resources/messages/technology_blip_de.properties

Update tech blips

---

src/main/java/com/a5lab/axion/domain/tenant/TenantServiceImpl.java
src/test/java/com/a5lab/axion/domain/AbstractServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java

Service tests with mock

---

pom.xml
src/main/java/com/a5lab/axion/domain/legal/LegalController.java
src/main/resources/templates/layouts/legal.html
src/test/java/com/a5lab/axion/domain/legal/LegalControllerTests.java

Create legal pages

---

src/main/java/com/a5lab/axion/domain/technology/TechnologyCfgController.java
src/main/java/com/a5lab/axion/domain/tenant/TenantCfgController.java
src/main/resources/database/data/technologies_en.csv
src/main/resources/templates/settings/technologies/index.html
src/main/resources/templates/settings/technologies/sorting.html
src/main/resources/templates/settings/tenants/index.html
src/main/resources/templates/settings/tenants/sorting.html

Add sorting

---

src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java

Added test for ring. Check for capital letters in the title and description

Add new create test

---

src/main/java/com/a5lab/axion/domain/segment/Segment.java
src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java

Add and create tests for SegmentCfgControllerTest

Add and create tests for SegmentCfgControllerTest

---

docs/modules/installation/pages/database_configuration.adoc

Add database info
@cherokee94 
* you can fix this page.

Add database info

---

docs/modules/installation/pages/installation_from_sources.adoc

@arufanov maybe we should rename "installation" to "deploy"? we don't install anything...

Installation from sources draft

---

src/main/java/com/a5lab/axion/domain/segment/SegmentRepository.java
src/main/java/com/a5lab/axion/domain/segment/SegmentServiceImpl.java
src/main/java/com/a5lab/axion/domain/tenant/TenantCfgController.java

Udpate filtering

---

src/main/resources/templates/fragments/main_navbar.html

@A9afon 
* could you review pr

Remove account from productin

---

src/main/resources/templates/settings/radars/show.html
src/main/resources/templates/settings/rings/show.html
src/main/resources/templates/settings/segments/show.html
src/main/resources/templates/settings/technologies/show.html
src/main/resources/templates/settings/technology_blips/show.html

URLs has been fixed

---

src/main/java/com/a5lab/axion/domain/ring/RingCfgController.java
src/main/java/com/a5lab/axion/domain/ring/RingRepository.java
src/main/java/com/a5lab/axion/domain/ring/RingServiceImpl.java

Update rings filtering

---

src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
src/main/java/com/a5lab/axion/domain/radar/RadarRepository.java
src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java

Fix radar filtering

---

src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java

Create tests for segments

---

src/test/java/com/a5lab/axion/domain/technology/TechnologyCfgControllerTests.java

Add some tests for technology: shouldGet\Show\RedirectShow\Add\Edit\RedirectEdit\Update\FailToUpdate\DeleteTechonology

Create tests for technology

---

src/test/java/com/a5lab/axion/domain/technologyBlip/TechnologyBlipCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

@arufanov Can you help me with this test? i tried to write a test "shouldGetTechnologyBlips" but i am having problems with Assertions.assertTrue (line 101-102)

Create tests for techonologyblip

---

docs/modules/installation/nav.adoc
docs/modules/installation/pages/installation_methods.adoc
docs/modules/release_notes/pages/0.1.0.adoc

Fixed some mistakes, because of them some text got lost

Fix markup mistakes

---

src/main/resources/templates/fragments/account_sidebar.html

Setup active menu item

---

src/test/java/com/a5lab/axion/domain/technology/TechnologyCfgControllerTests.java

Refactoring TechnologyCfgControllerTests done

Refactoring TechnologyCfgControllerTests done

---

src/main/resources/templates/settings/radars/fields.html
src/main/resources/templates/settings/rings/fields.html
src/main/resources/templates/settings/segments/fields.html
src/main/resources/templates/settings/technologies/fields.html
src/main/resources/templates/settings/technology_blips/fields.html

Remove common not global error

Remove common not global error

---

src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java

Refactoring RingCfgControllerTests done

Refactoring RingCfgControllerTests done

---

src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java

Refactoring SegmentCfgControllerTests done

Refactoring SegmentCfgControllerTests done

---

src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

Refactoring TechnologyBlipCfgControllerTests done

Refactoring TechnologyBlipCfgControllerTests done

---

src/main/java/com/a5lab/axion/domain/home/HomeController.java
src/main/java/com/a5lab/axion/domain/radar/Radar.java
src/main/java/com/a5lab/axion/domain/radar/RadarApiController.java
src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
src/main/java/com/a5lab/axion/domain/radar/RadarDto.java
src/main/java/com/a5lab/axion/domain/radar/RadarMapper.java
src/main/java/com/a5lab/axion/domain/radar/RadarService.java
src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
src/main/java/com/a5lab/axion/domain/segment/Segment.java
src/main/resources/templates/home/index.html
src/main/resources/templates/settings/radars/add.html
src/main/resources/templates/settings/radars/edit.html
src/main/resources/templates/settings/radars/index.html
src/main/resources/templates/settings/radars/paging.html
src/test/java/com/a5lab/axion/domain/home/HomeControllerTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarApiControllerTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarMapperTests.java

Fix: 410 button delete doesnt working

Fix: 410 button delete doesnt working

---

src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlip.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

Fix blips creation

---

src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

Fix strike

---

src/main/resources/templates/settings/radars/show.html
src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java

Added radar test

---

src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

Create test for cfg controller.

Explain how shouldcreatetechnologyblip works

---

src/test/java/com/a5lab/axion/domain/ring/RingApiControllerTests.java

Test fialed

---

src/test/java/com/a5lab/axion/domain/segment/SegmentApiControllerTests.java

Add test for segment

---

src/test/java/com/a5lab/axion/domain/technology/TechnologyApiControllerTests.java

Create api test for technology

Create api test for technology

---

src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java

Add tests for radar

---

src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipApiControllerTests.java

Add tests for technologyBlip

---

src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java

Create Service test for tenant

Create Service test for tenant

---

src/test/java/com/a5lab/axion/domain/ring/RingMapperTests.java

Create test for ring

---

src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java

Add test for RingService

---

src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java

Create test for segmentService

Create test for segmentService

---

src/test/java/com/a5lab/axion/domain/technology/TechnologyServiceTests.java

Create test for technology

---

src/main/resources/application-dev.yml
src/test/java/com/a5lab/axion/domain/AbstractAnyTests.java
src/test/java/com/a5lab/axion/domain/AbstractControllerTests.java
src/test/java/com/a5lab/axion/domain/AbstractRepositoryTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantRepositoryTests.java
src/test/resources/application-test.yml

Add locale for application-test

Add locale for application-test

---

pom.xml

Change line covered

---

src/main/java/com/a5lab/axion/domain/radar/Radar.java

Change updatable radar type for radar

---

src/main/java/com/a5lab/axion/utils/EntityToDtoMapper.java

Removing the object didn't change anything

Remove toDtoCollection

---

src/test/java/com/a5lab/axion/domain/home/HomeControllerTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarApiControllerTests.java
src/test/java/com/a5lab/axion/domain/ring/RingApiControllerTests.java
src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentApiControllerTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
src/test/java/com/a5lab/axion/domain/technology/TechnologyApiControllerTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantApiControllerTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java

@arufanov 
Test failed. Can you help me?

Test failed

---

src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
src/test/java/com/a5lab/axion/domain/technology/TechnologyServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java

Add pageable test for service

---

src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java

Create test for Radar

---

src/test/java/com/a5lab/axion/domain/radar/RadarMapperTests.java

Add mapper test for radar

---

src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapper.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapperTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java

Add test for technologyblip

---

src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapper.java
src/test/java/com/a5lab/axion/domain/AbstractMapperTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarMapperTests.java
src/test/java/com/a5lab/axion/domain/ring/RingMapperTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapperTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantMapperTests.java

Add uses for mapper

---

src/main/java/com/a5lab/axion/domain/wizard/WizardController.java
src/test/java/com/a5lab/axion/domain/wizard/WizardControllerTests.java

Create wizardcontroller Test

---

src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java

Fix and add more tests

---

pom.xml
src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology/TechnologyCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantCfgControllerTests.java

- Using Mockito for tests
- Adding FlashMassege

Update cfg tests

---

src/test/java/com/a5lab/axion/domain/wizard/WizardServiceTest.java

@arufonov
- see "TODO"
- let's discuss it

Add test file

---

src/test/java/com/a5lab/axion/domain/AbstractServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java

Test shouldSaveSegment is failed. 
```
java.lang.NullPointerException: Cannot invoke "com.a5lab.axion.domain.radar.RadarRepository.findById(java.lang.Long)" because "this.radarRepository" is null
```

Fix service test

---

src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java

Fix sevice test

---

src/test/java/com/a5lab/axion/domain/ring/RingMapperTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapperTests.java

Fix mapper test

---

src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java

Fix service test for radar

---

src/main/resources/application.yml

Fix warning

---

src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
src/test/java/com/a5lab/axion/domain/technology/TechnologyServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java

Fix compilation warning

---

pom.xml
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
src/test/java/com/a5lab/axion/domain/wizard/WizardServiceTest.java

Commented out tests wizard and tenant

Temporary fix

---

src/main/java/com/a5lab/axion/domain/radar/RadarMapper.java
src/test/java/com/a5lab/axion/domain/radar/RadarMapperTests.java

Empty website has been fixed

---

pom.xml
src/main/java/com/a5lab/axion/domain/ring/RingMapper.java
src/main/java/com/a5lab/axion/domain/segment/SegmentMapper.java
src/test/java/com/a5lab/axion/domain/radar/RadarMapperTests.java
src/test/java/com/a5lab/axion/domain/ring/RingMapperTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentMapperTests.java

The mapstruct uses are used for dto lists

The mapstruct uses are used for dto lists

---

src/test/java/com/a5lab/axion/domain/tenant/TenantCfgIntegrationTests.java

Tenant integration test has been implemented

Tenant integration test has been implemented

---

README.md

The GPG key configuration has been added

The GPG key configuration has been added

---

src/main/java/com/a5lab/axion/domain/radar/RadarMapper.java
src/main/java/com/a5lab/axion/domain/ring/RingMapper.java
src/main/java/com/a5lab/axion/domain/segment/SegmentMapper.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapper.java

Unmapped policy for mappers has been set

Unmapped policy for mappers has been set

---

README.md

Add checkstyle for PR

---

src/test/java/com/a5lab/axion/domain/ring/RingMapperTests.java

Add extra mockito for ringMapper

---

src/main/java/com/a5lab/axion/domain/radar_type/RadarType.java
src/main/java/com/a5lab/axion/domain/radar_type/RadarTypeDto.java
src/main/java/com/a5lab/axion/domain/radar_type/RadarTypeMapper.java

@arufanov 
Can you check this branch?
If everything is correct, can I fix the tests?
```
[ERROR] Tests run: 177, Failures: 0, Errors: 89, Skipped: 0
[ERROR]   RadarMapperTests.testToDtoAllFields » IllegalState Failed to load ApplicationC...
[ERROR]   RadarMapperTests.testToDtoAllLists » IllegalState Failed to load ApplicationCo...
[ERROR]   RadarMapperTests.testToDtoWithNull » IllegalState Failed to load ApplicationCo...
[ERROR]   RadarMapperTests.testToEntityAllFields » IllegalState Failed to load Applicati...
[ERROR]   RadarMapperTests.testToEntityAllLists » IllegalState Failed to load Applicatio...
[ERROR]   RadarMapperTests.testToEntityWithNull » IllegalState Failed to load Applicatio...
[ERROR]   RadarRepositoryTests.shouldFailOnEmptyDescription » IllegalState Failed to loa... …
```

Add radarList

---

src/main/resources/application.yml
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
src/test/java/com/a5lab/axion/domain/wizard/WizardServiceTest.java
src/test/resources/application-test.yml

Spring boot context and pool connection has been reconfigured

Spring boot context and pool connection has been reconfigured

---

docs/modules/installation/pages/application_configuration.adoc
src/main/java/com/a5lab/axion/config/ViewAttributesConfiguration.java
src/main/resources/application.yml
src/main/resources/templates/fragments/yandex_metrika.html
src/main/resources/templates/layouts/account.html
src/main/resources/templates/layouts/exception.html
src/main/resources/templates/layouts/home.html
src/main/resources/templates/layouts/legal.html
src/main/resources/templates/layouts/radar.html
src/main/resources/templates/layouts/settings.html
src/main/resources/templates/layouts/simple.html
src/main/resources/templates/layouts/wizard.html

Yandex metrika has been added

---

pom.xml
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipDto.java
src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
src/test/java/com/a5lab/axion/domain/radar_type/RadarTypeServiceTests.java
src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
src/test/java/com/a5lab/axion/domain/technology/TechnologyServiceTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceTests.java
src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
src/test/java/com/a5lab/axion/domain/wizard/WizardControllerTests.java

Coverage ratio has been increased

Coverage ratio has been increased

---

docs/modules/best_practices/pages/administration_best_practices.adoc
docs/modules/installation/pages/installation_prerequisites.adoc

The documentation has been fixed

The documentation has been fixed

---

src/main/java/com/a5lab/axion/domain/ring/RingDto.java
src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java

Additional validation has been implement

Additional validation has been implement

---

src/main/java/com/a5lab/axion/domain/home/HomeController.java
src/main/java/com/a5lab/axion/domain/radar/RadarRepository.java
src/main/java/com/a5lab/axion/domain/radar/RadarService.java
src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
src/test/java/com/a5lab/axion/domain/home/HomeControllerTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java

FindByPrimaryAndActive has been removed

FindByPrimaryAndActive has been removed

---

src/main/java/com/a5lab/axion/domain/ring/Ring.java
src/main/java/com/a5lab/axion/domain/segment/Segment.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlip.java
src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

The listdto has been updatabled

The listdto has been updatabled

---

pom.xml
src/main/java/com/a5lab/axion/domain/radar/RadarDto.java
src/main/java/com/a5lab/axion/domain/radar/RadarMapper.java
src/main/java/com/a5lab/axion/domain/ring/RingDto.java
src/main/java/com/a5lab/axion/domain/ring/RingMapper.java
src/main/java/com/a5lab/axion/domain/segment/SegmentDto.java
src/main/java/com/a5lab/axion/domain/segment/SegmentMapper.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipDto.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipMapper.java
src/main/java/com/a5lab/axion/domain/wizard/WizardDto.java

The mapper expressions has been refactored

The mapper expressions has been refactored

---

pom.xml
src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
src/main/java/com/a5lab/axion/domain/radar/RadarRepository.java
src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
src/main/java/com/a5lab/axion/domain/radar/RadarUniqueTitleApprover.java
src/main/resources/messages/radar.properties
src/main/resources/messages/radar_de.properties
src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/radar/RadarRepositoryTests.java

The unique title approver has been added

The unique title approver has been added

---

src/main/java/com/a5lab/axion/domain/ring/RingCfgController.java
src/main/java/com/a5lab/axion/domain/segment/SegmentCfgController.java
src/test/java/com/a5lab/axion/domain/tenant/TenantRepositoryTests.java

The hibernate patImp has been removed

The hibernate patImp has been removed

---

src/main/java/com/a5lab/axion/domain/ValidationException.java
src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
src/main/java/com/a5lab/axion/domain/ring/RadarActiveApprover.java
src/main/java/com/a5lab/axion/domain/ring/RingServiceImpl.java
src/main/java/com/a5lab/axion/domain/segment/RadarActiveApprover.java
src/main/java/com/a5lab/axion/domain/segment/SegmentServiceImpl.java
src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java

The ring and segment delete of active radar has been fixed

The ring and segment delete of active radar has been fixed

---

src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java

Field related error has been tested

Field related error has been tested

---

src/test/java/com/a5lab/axion/domain/wizard/WizardServiceTest.java

The Wizard test has been fixed

The Wizard test has been fixed

---

pom.xml
src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
src/main/java/com/a5lab/axion/domain/ring/RingCfgController.java
src/main/java/com/a5lab/axion/domain/segment/SegmentCfgController.java

The bind result for radar, segment, ring has been removed

The bind result for radar, segment, ring has been removed

---

pom.xml
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgController.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipRepository.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipServiceImpl.java
src/main/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipUniqueFieldsSaveApprover.java
src/main/resources/messages/technology_blip.properties
src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java

The data integrity violation exception has been removed from technology blips

The data integrity violation exception has been removed from technology blips

---

pom.xml
src/main/java/com/a5lab/axion/domain/ring/RadarActiveSaveApprover.java
src/main/java/com/a5lab/axion/domain/ring/RingServiceImpl.java
src/main/java/com/a5lab/axion/domain/segment/RadarActiveSaveApprover.java
src/main/java/com/a5lab/axion/domain/segment/SegmentServiceImpl.java
src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java

The ring and segment validation have been implemented

The ring and segment validation have been implemented

---

src/main/java/com/a5lab/axion/domain/ring/RadarActiveSaveApprover.java
src/main/java/com/a5lab/axion/domain/ring/RingServiceImpl.java
src/main/java/com/a5lab/axion/domain/segment/RadarActiveSaveApprover.java
src/main/java/com/a5lab/axion/domain/segment/SegmentServiceImpl.java

The ring creation has been fixed

The ring creation has been fixed

---

src/test/java/com/a5lab/axion/domain/tenant/TenantServiceRepositoryTests.java

The tenant filter has been covered

The tenant filter has been covered

---

docs/modules/release_notes/nav.adoc
docs/modules/release_notes/pages/0.1.0.adoc
docs/modules/release_notes/pages/0.2.0.adoc
docs/modules/release_notes/pages/0.3.0.adoc
docs/modules/release_notes/pages/overview.adoc

The release notes has been added

The release notes has been added

---

.github/workflows/package.yml
.github/workflows/verify.yml
pom.xml

Jdk 21 is supporter

---

.github/workflows/package.yml
.github/workflows/verify.yml
.gitignore
README.md
package-lock.json
package.json
pom.xml

The node module uglify have beed added

The node module uglify have beed added
